services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      .env
    ports:
      - 3000:3000
    volumes:
      - /home/nate/Dev/homelab/homepage/app/config:/app/config
      - /home/nate/Dev/homelab/homepage/src/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      - homelab-net

