---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Quick Links:
  - Proton:
    - icon: si-proton
      href: https://account.proton.me/apps

  - YouTube:
    - icon: si-youtube
      href: https://youtube.com

  - Github:
    - icon: si-github
      href: https://github.com/Nate-Cheney?tab=repositories

  - Gemini:
    - icon: si-googlegemini
      href: https://gemini.google.com/app

  - Tailscale:
    - icon: si-tailscale
      href: https://login.tailscale.com/admin/machines

  - Cloudflare:
    - icon: si-cloudflare
      href: https://dash.cloudflare.com
