---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Homelab:
    - Immich:
        icon: immich.svg
        href: https://immich.cheney.win/photos
        description: Self-hosted photo and video management

