---

- Homelab:
    - Immich:
        icon: immich.svg
        href: https://immich.cheney.win/photos
        description: Self-hosted photo and video management

    - Linkding:
        icon: linkding.svg
        href: https://linkding.cheney.win/bookmarks
        description: Self-hosted bookmark manager

