---

theme: dark
color: gray 
headerStyle: clean

background:
  image: images/small_zion.jpg
  blur: sm
  brightness: 75
  opacity: 50

layout:
  Quick Links:
    style: row
    columns: 3


providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
